
services:
  - type: web
    name: ndvi-viewer
    env: docker
    plan: starter
    region: singapore
    autoDeploy: true
    healthCheckPath: /healthz
    envVars:
      - key: EE_PROJECT
        sync: false
      - key: EE_SERVICE_ACCOUNT_EMAIL
        sync: false
      - key: GOOGLE_APPLICATION_CREDENTIALS_JSON
        sync: false
      - key: FIRESTORE_PROJECT_ID
        sync: false
