services:
  - type: web
    name: gee-indices-exporter
    env: python
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: EE_SERVICE_ACCOUNT_EMAIL
        sync: false
      - key: EE_PROJECT
        sync: false
      - key: GCS_BUCKET
        sync: false
      - key: GOOGLE_APPLICATION_CREDENTIALS_JSON
        sync: false
